import * as Print from "expo-print";

export interface SensorLog {
  id: string;
  pm25: number;
  gas: number;
  humidity: number;
  temperature: number;
  timestamp: string;
}

/**
 * Format date to readable string
 */
export const formatDate = (timestamp: string): string => {
  return new Date(timestamp).toLocaleString();
};

/**
 * Generate HTML content for sensor history PDF report
 */
export const generatePDFHTML = (data: SensorLog[]): string => {
  const reportHTML = `
    <html>
      <head>
        <style>
          body { 
            font-family: Arial, sans-serif; 
            margin: 20px; 
            color: #333; 
          }
          h1 { 
            color: #1e40af; 
            border-bottom: 2px solid #3b82f6; 
            padding-bottom: 10px; 
          }
          .info { 
            margin: 10px 0; 
            font-size: 12px; 
            color: #666; 
          }
          table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px; 
          }
          th { 
            background: #3b82f6; 
            color: white; 
            padding: 10px; 
            text-align: left; 
            font-weight: bold; 
          }
          td { 
            padding: 10px; 
            border-bottom: 1px solid #e5e7eb; 
          }
          tr:nth-child(even) { 
            background: #f9fafb; 
          }
          .sensor-value { 
            font-weight: bold; 
            color: #1e40af; 
          }
          .footer {
            margin-top: 30px; 
            font-size: 10px; 
            color: #999; 
            border-top: 1px solid #e5e7eb; 
            padding-top: 10px;
          }
        </style>
      </head>
      <body>
        <h1>📊 SENSOR HISTORY REPORT</h1>
        <div class="info">
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Total Records:</strong> ${data.length}</p>
          <p><strong>Date Range:</strong> ${formatDate(data[data.length - 1]?.timestamp)} to ${formatDate(data[0]?.timestamp)}</p>
        </div>
        <table>
          <thead>
            <tr>
              <th>Date & Time</th>
              <th>PM2.5 (µg/m³)</th>
              <th>Gas (ppm)</th>
              <th>Humidity (%)</th>
              <th>Temp (°C)</th>
            </tr>
          </thead>
          <tbody>
            ${data
              .map(
                (log) => `
              <tr>
                <td>${formatDate(log.timestamp)}</td>
                <td><span class="sensor-value">${log.pm25}</span></td>
                <td><span class="sensor-value">${log.gas}</span></td>
                <td><span class="sensor-value">${log.humidity}</span></td>
                <td><span class="sensor-value">${log.temperature}</span></td>
              </tr>
            `,
              )
              .join("")}
          </tbody>
        </table>
        <p class="footer">
          This report was auto-generated by Dust Monitoring System
        </p>
      </body>
    </html>
  `;

  return reportHTML;
};

/**
 * Export sensor history as PDF with save dialog
 */
export const exportSensorHistoryPDF = async (
  data: SensorLog[],
): Promise<string> => {
  if (data.length === 0) {
    throw new Error("No data to export");
  }

  try {
    const html = generatePDFHTML(data);

    // Open print dialog where user can save as PDF
    await Print.printAsync({
      html,
      // This allows user to select "Save as PDF" on Android
      // and "Save PDF" on iOS
    });

    console.log("✅ PDF export dialog opened");
    return "Save dialog opened! Choose where to save the PDF.";
  } catch (error) {
    // User cancelled - this is not an error
    if (error instanceof Error && error.message.includes("cancelled")) {
      console.log("User cancelled PDF export");
      return "PDF export cancelled";
    }

    if (error instanceof Error) {
      throw error;
    }
    throw new Error("Failed to export PDF");
  }
};
